%series
%contenido(id,nombre,genero,año,psinopsis,capitulos,actores,idiomas)
%Generos_Series
%drama
serie(1, 'La Reina de las lágrimas', drama, 2023, 'La historia gira en torno a Baek Hyun-woo y Hong Hae-in, el matrimonio encarnado por Kim Soo-hyun y Kim Ji-won que encara una verdadera montaña rusa de emociones.', 16, 'Kim Ji Won, Kim Soo-hyun', 'Coreano y Español').
serie(2, 'El Rey Eterno', drama, 2020, 'Un emperador de Corea intenta cerrar la puerta al mundo paralelo que ha sido abierta por los demonios. Protagonizada por Lee Min-ho y Kim Go-eun, la serie explora temas de amor y destino a través de dos mundos diferentes.', 16, 'Lee Min-ho, Kim Go-eun', 'Coreano y Español').
serie(3, 'A Korean Odyssey', drama, 2017, 'En una moderna reinterpretación de la clásica novela china "Viaje al Oeste", un hombre busca a una mujer con poderes especiales para obtener su ayuda. Protagonizada por Lee Seung-gi y Oh Yeon-seo, la serie combina elementos de fantasía y romance.', 20, 'Lee Seung-gi, Oh Yeon-seo', 'Coreano y Español').
serie(4, 'Está bien no estar bien', drama, 2020, 'Un trabajador de salud mental y una escritora de libros infantiles enfrentan sus propios traumas mientras forman una conexión inesperada. Protagonizada por Kim Soo-hyun y Seo Ye-ji, la serie aborda temas de sanación emocional y amor.', 16, 'Kim Soo-hyun, Seo Ye-ji', 'Coreano y Español').
serie(5, 'El amor es como el cha-cha-chá', drama, 2021, 'Una dentista de ciudad se muda a un pintoresco pueblo costero y conoce a un hombre multifacético que se convierte en su apoyo. Protagonizada por Shin Min-ah y Kim Seon-ho, la serie es una mezcla de romance y comedia.', 16, 'Shin Min-ah, Kim Seon-ho', 'Coreano y Español').
serie(6, 'El jardín de meteoros', drama, 2018, 'Una estudiante de secundaria se encuentra en medio de un triángulo amoroso con dos miembros de un grupo elitista en su escuela. Protagonizada por Shen Yue y Dylan Wang, esta serie es una adaptación del popular manga "Boys Over Flowers".', 49, 'Shen Yue, Dylan Wang', 'Mandarín y Español').
serie(7, 'Recuérdame', drama, 2015, 'Una joven con amnesia intenta reconstruir su vida con la ayuda de un enigmático hombre que parece conocer todos sus secretos. Protagonizada por Seo In-guk y Jang Na-ra, la serie mezcla misterio y romance en un cautivador relato.', 16, 'Seo In-guk, Jang Na-ra', 'Coreano y Español').
serie(8, 'El juego del calamar', drama, 2021, 'Desesperados por dinero, un grupo de personas acepta participar en juegos infantiles con mortales consecuencias. Protagonizada por Lee Jung-jae y Park Hae-soo, la serie es un intenso thriller que explora la desesperación humana.', 9, 'Lee Jung-jae, Park Hae-soo', 'Coreano y Español').
serie(9, 'Vincenzo', drama, 2021, 'Un abogado coreano-italiano regresa a Corea y se enfrenta a la mafia para recuperar un botín escondido. Protagonizada por Song Joong-ki y Jeon Yeo-been, la serie mezcla acción, drama y comedia negra.', 20, 'Song Joong-ki, Jeon Yeo-been', 'Coreano y Español').
serie(10, 'Mi señor', drama, 2018, 'Un hombre de mediana edad y una joven mujer con dificultades económicas encuentran consuelo en su inusual amistad. Protagonizada por Lee Sun-kyun y IU, la serie aborda temas de soledad y esperanza.', 16, 'Lee Sun-kyun, IU', 'Coreano y Español').
%ciencia_ficcion
serie(11, 'Stranger Things', ciencia ficción, 2016, 'Un grupo de niños en un pequeño pueblo descubre un laboratorio secreto y una dimensión paralela mientras buscan a su amigo desaparecido. Protagonizada por Millie Bobby Brown y Finn Wolfhard, la serie combina misterio, terror y aventuras.', 34, 'Millie Bobby Brown, Finn Wolfhard', 'Inglés y Español').
serie(12, 'Dark', ciencia ficción, 2017, 'En un pequeño pueblo alemán, la desaparición de dos niños expone los secretos y conexiones entre cuatro familias mientras descubren un siniestro misterio que abarca tres generaciones. Protagonizada por Louis Hofmann y Lisa Vicari, la serie explora viajes en el tiempo y paradojas.', 26, 'Louis Hofmann, Lisa Vicari', 'Alemán y Español').
serie(13, 'The Umbrella Academy', ciencia ficción, 2019, 'Un grupo de hermanos adoptivos con habilidades extraordinarias se reúne tras la muerte de su padre adoptivo y se enfrenta a una amenaza apocalíptica. Protagonizada por Elliot Page y Tom Hopper, la serie combina drama familiar y superhéroes.', 30, 'Elliot Page, Tom Hopper', 'Inglés y Español').
serie(14, 'Black Mirror', ciencia ficción, 2011, 'Cada episodio de esta antología explora un futuro distópico o una versión alternativa de nuestra realidad, reflejando los peligros de la tecnología y la sociedad. Creada por Charlie Brooker, la serie presenta historias independientes y provocativas.', 22, 'Varios', 'Inglés y Español').
serie(15, 'Altered Carbon', ciencia ficción, 2018, 'En un futuro donde la conciencia humana puede transferirse a diferentes cuerpos, un ex-soldado es resucitado para resolver un asesinato. Protagonizada por Joel Kinnaman y Anthony Mackie, la serie explora temas de identidad y mortalidad.', 18, 'Joel Kinnaman, Anthony Mackie', 'Inglés y Español').
serie(16, 'The OA', ciencia ficción, 2016, 'Una joven ciega desaparecida regresa con su vista restaurada y extrañas habilidades, embarcándose en una misión para rescatar a otras personas desaparecidas. Protagonizada por Brit Marling y Jason Isaacs, la serie mezcla misterio, ciencia ficción y espiritualidad.', 16, 'Brit Marling, Jason Isaacs', 'Inglés y Español').
serie(17, 'Sense8', ciencia ficción, 2015, 'Ocho desconocidos de diferentes partes del mundo descubren que están mental y emocionalmente conectados, y deben unirse para enfrentar una amenaza global. Protagonizada por Doona Bae y Jamie Clayton, la serie celebra la diversidad y la conexión humana.', 24, 'Doona Bae, Jamie Clayton', 'Inglés y Español').
serie(18, 'Lost in Space', ciencia ficción, 2018, 'Tras un aterrizaje forzoso en un planeta desconocido, la familia Robinson debe luchar contra un entorno hostil y resolver misterios para sobrevivir y escapar. Protagonizada por Molly Parker y Toby Stephens, la serie es una aventura de supervivencia espacial.', 28, 'Molly Parker, Toby Stephens', 'Inglés y Español').
serie(19, 'Travelers', ciencia ficción, 2016, 'Un grupo de personas del futuro envía sus conciencias al presente para evitar un desastre global, ocupando los cuerpos de individuos a punto de morir. Protagonizada por Eric McCormack y MacKenzie Porter, la serie combina elementos de espionaje y ciencia ficción.', 34, 'Eric McCormack, MacKenzie Porter', 'Inglés y Español').
serie(20, 'The 100', ciencia ficción, 2014, 'Cien jóvenes delincuentes son enviados a la Tierra desde una estación espacial para ver si es habitable después de un apocalipsis nuclear. Protagonizada por Eliza Taylor y Bob Morley, la serie explora la supervivencia y la reconstrucción de la civilización.', 100, 'Eliza Taylor, Bob Morley', 'Inglés y Español').
%aventuras
serie(21, 'La Casa de Papel', aventura, 2017, 'Un grupo de criminales planea y ejecuta un ambicioso robo a la Fábrica Nacional de Moneda y Timbre de España, guiados por el enigmático "El Profesor". Protagonizada por Álvaro Morte y Úrsula Corberó, la serie es una emocionante mezcla de suspense y estrategia.', 31, 'Álvaro Morte, Úrsula Corberó', 'Español').
serie(22, 'The Witcher', aventura, 2019, 'Geralt de Rivia, un cazador de monstruos solitario, lucha por encontrar su lugar en un mundo donde las personas a menudo son más perversas que las bestias. Protagonizada por Henry Cavill y Anya Chalotra, la serie es una épica de fantasía basada en las novelas de Andrzej Sapkowski.', 24, 'Henry Cavill, Anya Chalotra', 'Inglés y Español').
serie(23, 'Avatar: The Last Airbender', aventura, 2005, 'En un mundo dividido en cuatro naciones elementales, un joven Avatar debe aprender a dominar los cuatro elementos y detener la guerra que amenaza con destruir el mundo. Protagonizada por Zach Tyler Eisen y Mae Whitman, la serie combina aventura y filosofía.', 61, 'Zach Tyler Eisen, Mae Whitman', 'Inglés y Español').
serie(24, 'Marco Polo', aventura, 2014, 'Basada en las aventuras del famoso explorador veneciano, la serie sigue a Marco Polo en la corte de Kublai Khan en la antigua Mongolia. Protagonizada por Lorenzo Richelmy y Benedict Wong, la serie ofrece una rica exploración histórica y cultural.', 20, 'Lorenzo Richelmy, Benedict Wong', 'Inglés y Español').
serie(25, 'Lost', aventura, 2004, 'Los sobrevivientes de un accidente aéreo se encuentran en una misteriosa isla tropical llena de secretos y peligros. Protagonizada por Matthew Fox y Evangeline Lilly, la serie combina elementos de aventura, ciencia ficción y drama.', 121, 'Matthew Fox, Evangeline Lilly', 'Inglés y Español').
serie(26, 'Outer Banks', aventura, 2020, 'Un grupo de adolescentes en los Outer Banks de Carolina del Norte descubre un antiguo misterio y se embarca en una peligrosa búsqueda del tesoro. Protagonizada por Chase Stokes y Madelyn Cline, la serie es una emocionante mezcla de aventuras y drama adolescente.', 30, 'Chase Stokes, Madelyn Cline', 'Inglés y Español').
serie(27, 'The Mandalorian', aventura, 2019, 'Un cazarrecompensas solitario en la galaxia de Star Wars se encuentra cuidando a un misterioso niño con poderes especiales mientras enfrenta peligros y enemigos en cada rincón. Protagonizada por Pedro Pascal, la serie es una épica espacial llena de acción.', 24, 'Pedro Pascal', 'Inglés y Español').
serie(28, 'Black Sails', aventura, 2014, 'Una precuela de "La Isla del Tesoro" que sigue las aventuras del Capitán Flint y su tripulación mientras luchan por la supervivencia y el control de Nassau. Protagonizada por Toby Stephens y Hannah New, la serie ofrece acción y drama en el mundo de la piratería.', 38, 'Toby Stephens, Hannah New', 'Inglés y Español').
serie(29, 'Into the Badlands', aventura, 2015, 'En un futuro feudal post-apocalíptico, un guerrero y un joven se embarcan en un viaje por una peligrosa tierra gobernada por barones feudales. Protagonizada por Daniel Wu y Emily Beecham, la serie es conocida por sus impresionantes coreografías de artes marciales.', 32, 'Daniel Wu, Emily Beecham', 'Inglés y Español').
serie(30, 'Robin Hood', aventura, 2006, 'Una reinterpretación moderna del clásico héroe del folklore inglés, Robin Hood lucha contra la corrupción y la tiranía en el Bosque de Sherwood. Protagonizada por Jonas Armstrong y Lucy Griffiths, la serie mezcla acción, aventura y romance.', 39, 'Jonas Armstrong, Lucy Griffiths', 'Inglés y Español').
%terrorSerie
serie(31, 'The Haunting of Hill House', terror, 2018, 'Una familia enfrenta los traumas del pasado mientras lidia con los espíritus que acechan en la antigua mansión en la que crecieron. Protagonizada por Michiel Huisman y Elizabeth Reaser, la serie es una adaptación del clásico de Shirley Jackson.', 10, 'Michiel Huisman, Elizabeth Reaser', 'Inglés y Español').
serie(32, 'American Horror Story', terror, 2011, 'Cada temporada presenta una nueva historia independiente, explorando diferentes temas de horror que van desde casas encantadas hasta cultos y circos macabros. Creada por Ryan Murphy y Brad Falchuk, la serie cuenta con un elenco rotativo de talentosos actores.', 10, 'Varios', 'Inglés y Español').
serie(33, 'The Walking Dead', terror, 2010, 'Un grupo de supervivientes lucha por sobrevivir en un mundo post-apocalíptico lleno de zombies y amenazas humanas. Basada en el cómic de Robert Kirkman, la serie es conocida por su intensidad emocional y sus impactantes escenas de acción.', 177, 'Andrew Lincoln, Norman Reedus', 'Inglés y Español').
serie(34, 'Penny Dreadful', terror, 2014, 'Personajes de la literatura de terror victoriana, como el Dr. Frankenstein y Dorian Gray, se encuentran en un mundo oscuro lleno de monstruos y brujería. Protagonizada por Eva Green y Josh Hartnett, la serie es una amalgama de horror gótico y drama.', 27, 'Eva Green, Josh Hartnett', 'Inglés y Español').
serie(35, 'The Terror', terror, 2018, 'Basada en la novela de Dan Simmons, la serie sigue a una expedición polar británica atrapada en el hielo mientras son acosados por un misterioso depredador. Protagonizada por Jared Harris y Tobias Menzies, la serie es una mezcla de horror sobrenatural y drama histórico.', 10, 'Jared Harris, Tobias Menzies', 'Inglés y Español').
%anime
serie(36, 'Attack on Titan', anime, 2013, 'En un mundo donde la humanidad está al borde de la extinción debido a gigantes devoradores de humanos conocidos como "Titanes", un joven llamado Eren Yeager se une a la lucha para proteger a la humanidad y descubrir los secretos detrás de los titanes. Protagonizada por Yuki Kaji y Yui Ishikawa, la serie es conocida por su intensa acción y trama emocionalmente cargada.', 75, 'Yuki Kaji, Yui Ishikawa', 'Japonés y Español').
serie(37, 'Naruto', anime, 2002, 'Naruto Uzumaki, un joven ninja con grandes sueños de convertirse en el líder de su aldea y ser reconocido como el más grande de todos los tiempos, se embarca en una aventura épica llena de acción, amistad y sacrificio. Protagonizada por Junko Takeuchi y Maile Flanagan, la serie es una de las más populares y duraderas del anime.', 220, 'Junko Takeuchi, Maile Flanagan', 'Japonés y Español').
serie(38, 'One Piece', anime, 1999, 'Monkey D. Luffy y su tripulación de piratas navegan por el vasto océano en busca del legendario tesoro conocido como "One Piece", enfrentándose a poderosos enemigos, formando nuevas amistades y viviendo emocionantes aventuras en el camino. Protagonizada por Mayumi Tanaka y Colleen Clinkenbeard, la serie es conocida por su vasto mundo y su sentido del humor.', 1000+, 'Mayumi Tanaka, Colleen Clinkenbeard', 'Japonés y Español').
serie(39, 'Death Note', anime, 2006, 'Cuando un brillante estudiante de secundaria llamado Light Yagami encuentra un cuaderno que otorga el poder de matar a cualquier persona cuyo nombre sea escrito en él, se embarca en una misión para limpiar el mundo de criminales y convertirse en el nuevo dios del nuevo mundo. Protagonizada por Mamoru Miyano y Brad Swaile, la serie es un emocionante thriller psicológico.', 37, 'Mamoru Miyano, Brad Swaile', 'Japonés y Español').
serie(40, 'Fullmetal Alchemist: Brotherhood', anime, 2009, 'Dos hermanos alquimistas, Edward y Alphonse Elric, buscan la piedra filosofal para restaurar sus cuerpos después de un intento fallido de resucitar a su madre usando la alquimia. En su viaje, descubren una conspiración que amenaza con sumir al mundo en el caos. Protagonizada por Romi Park y Vic Mignogna, la serie es una adaptación fiel y emocionante del manga.', 64, 'Romi Park, Vic Mignogna', 'Japonés y Español').
serie(41, 'Demon Slayer: Kimetsu no Yaiba', anime, 2019, 'Tanjiro Kamado, un joven cazador de demonios, se embarca en una peligrosa misión para vengar la muerte de su familia y curar a su hermana Nezuko, quien ha sido convertida en un demonio. Protagonizada por Natsuki Hanae y Zach Aguilar, la serie es conocida por su impresionante animación y emocionantes batallas.', 26, 'Natsuki Hanae, Zach Aguilar', 'Japonés y Español').
serie(42, 'My Hero Academia', anime, 2016, 'En un mundo donde la mayoría de la población posee superpoderes llamados "Quirks", un joven sin poderes llamado Izuku Midoriya sueña con convertirse en un héroe como su ídolo, All Might. Cuando recibe el Quirk de su héroe, se une a la academia de héroes para entrenar y convertirse en el mejor héroe. Protagonizada por Daiki Yamashita y Justin Briner, la serie es una emocionante aventura llena de acción y emociones.', 113, 'Daiki Yamashita, Justin Briner', 'Japonés y Español').
serie(43, 'Hunter x Hunter', anime, 2011, 'Gon Freecss, un joven aventurero, se embarca en una búsqueda para encontrar a su padre ausente, quien es un legendario cazador de tesoros. En el camino, hace nuevos amigos, enfrenta peligrosos desafíos y descubre los secretos del mundo de los cazadores. Protagonizada por Megumi Han y Erica Mendez, la serie es una emocionante historia de aventuras y amistad.', 148, 'Megumi Han, Erica Mendez', 'Japonés y Español').
serie(44, 'Tokyo Ghoul', anime, 2014, 'Kaneki Ken, un joven universitario, es transformado en mitad ghoul, una especie de criatura carnívora que se oculta entre los humanos, después de un encuentro con una ghoul enmascarada. Ahora, debe aprender a vivir en este nuevo mundo mientras lucha por mantener su humanidad. Protagonizada por Natsuki Hanae y Austin Tindle, la serie es una oscura y emocionante exploración de la identidad y la supervivencia.', 48, 'Natsuki Hanae, Austin Tindle', 'Japonés y Español').
serie(45, 'Sword Art Online', anime, 2012, 'En un futuro cercano, los jugadores de un popular juego de realidad virtual llamado "Sword Art Online" se encuentran atrapados dentro del juego por su creador. El protagonista, Kirito, debe navegar a través del mundo del juego y luchar por su supervivencia mientras busca una manera de escapar. Protagonizada por Yoshitsugu Matsuoka y Bryce Papenbrook, la serie es una emocionante aventura de acción y drama.', 97, 'Yoshitsugu Matsuoka, Bryce Papenbrook', 'Japonés y Español').
%comedia
serie(46, 'KonoSuba: Gods Blessing on This Wonderful World!', anime, 2016, 'Kazuma Satou, un joven que muere de manera ridícula, es transportado a un mundo de fantasía donde forma un grupo disfuncional con una diosa inútil, una hechicera obsesionada con explosiones y una cruzada masoquista. Protagonizada por Jun Fukushima y Sora Amamiya, la serie es una hilarante comedia de fantasía.', 20, 'Jun Fukushima, Sora Amamiya', 'Japonés y Español').
serie(47, 'Ouran High School Host Club', anime, 2006, 'Haruhi Fujioka, una estudiante de clase baja en la prestigiosa Academia Ouran, accidentalmente se convierte en miembro del Host Club de la escuela, un grupo de chicos que entretienen a las chicas del instituto. Protagonizada por Maaya Sakamoto y Mamoru Miyano, la serie es una encantadora comedia romántica.', 26, 'Maaya Sakamoto, Mamoru Miyano', 'Japonés y Español').
serie(48, 'Gintama', anime, 2006, 'En un Japón alternativo donde los samuráis luchan contra una invasión alienígena, Gintoki Sakata y su equipo de inadaptados toman trabajos extraños para llegar a fin de mes. Protagonizada por Tomokazu Sugita y Daisuke Sakaguchi, la serie combina comedia absurda con emocionantes batallas.', 367, 'Tomokazu Sugita, Daisuke Sakaguchi', 'Japonés y Español').
serie(49, 'Nichijou', anime, 2011, 'La serie sigue las vidas absurdamente cotidianas de un grupo de estudiantes y su robot con conciencia, Nano. Protagonizada por Mariko Honda y Mai Aizawa, la serie es conocida por su estilo de humor surrealista y exagerado.', 26, 'Mariko Honda, Mai Aizawa', 'Japonés y Español').
serie(50, 'The Disastrous Life of Saiki K.', anime, 2016, 'Kusuo Saiki, un estudiante de secundaria con poderes psíquicos, intenta llevar una vida normal a pesar de las constantes interrupciones causadas por sus habilidades y sus excéntricos compañeros de clase. Protagonizada por Hiroshi Kamiya y Daisuke Ono, la serie es una comedia de situaciones sobrenaturales.', 120, 'Hiroshi Kamiya, Daisuke Ono', 'Japonés y Español').
serie(51, 'Great Teacher Onizuka', anime, 1999, 'Eikichi Onizuka, un ex pandillero de 22 años, se convierte en profesor con la intención de ser el mejor maestro del mundo, a pesar de sus métodos poco convencionales y su comportamiento a menudo inapropiado. Protagonizada por Takagi Wataru y Shigeru Chiba, la serie es una comedia dramática con toques de acción.', 43, 'Takagi Wataru, Shigeru Chiba', 'Japonés y Español').
serie(52, 'Monthly Girls Nozaki-kun', anime, 2014, 'Chiyo Sakura, una estudiante de secundaria, descubre que su amor platónico, Umetarou Nozaki, es un popular autor de manga shoujo. Ella se convierte en su asistente en un intento de acercarse a él. Protagonizada por Ari Ozawa y Yuichi Nakamura, la serie es una divertida comedia romántica.', 12, 'Ari Ozawa, Yuichi Nakamura', 'Japonés y Español').
serie(53, 'School Rumble', anime, 2004, 'La vida amorosa y escolar de Tenma Tsukamoto se complica cuando trata de confesar sus sentimientos a su compañero de clase mientras Kenji Harima, un delincuente reformado, intenta confesarle su amor a ella. Protagonizada por Ami Koshimizu y Hiroki Takahashi, la serie es una comedia romántica llena de malentendidos y situaciones hilarantes.', 52, 'Ami Koshimizu, Hiroki Takahashi', 'Japonés y Español').
serie(54, 'Azumanga Daioh', anime, 2002, 'La serie sigue las vidas de un grupo de chicas de secundaria y sus peculiares profesores mientras enfrentan las travesuras cotidianas y las extrañas situaciones de la vida escolar. Protagonizada por Tomoko Kaneda y Yuki Matsuoka, la serie es una encantadora comedia de la vida diaria.', 26, 'Tomoko Kaneda, Yuki Matsuoka', 'Japonés y Español').
%suspenso
serie(55, 'Stranger Things', suspenso, 2016, 'En la ciudad de Hawkins, Indiana, un grupo de niños busca a su amigo desaparecido y descubre una niña con poderes psíquicos y una oscura conspiración gubernamental. Protagonizada por Winona Ryder y David Harbour, la serie es conocida por su atmósfera nostálgica de los años 80 y su emocionante trama.', 34, 'Winona Ryder, David Harbour', 'Inglés y Español').
serie(56, 'Mindhunter', suspenso, 2017, 'Ambientada en los años 70, la serie sigue a dos agentes del FBI, Holden Ford y Bill Tench, que desarrollan técnicas de perfilación criminal al entrevistar a asesinos en serie. Protagonizada por Jonathan Groff y Holt McCallany, la serie es un thriller psicológico basado en hechos reales.', 19, 'Jonathan Groff, Holt McCallany', 'Inglés y Español').
serie(57, 'Ozark', suspenso, 2017, 'Marty Byrde, un asesor financiero, se muda con su familia a los Ozarks para lavar dinero para un cartel de drogas mexicano. Protagonizada por Jason Bateman y Laura Linney, la serie es conocida por su tensa narrativa y complejas tramas de crimen y moralidad.', 44, 'Jason Bateman, Laura Linney', 'Inglés y Español').
serie(58, 'True Detective', suspenso, 2014, 'Cada temporada presenta una historia y un elenco diferente, explorando oscuros crímenes en varios lugares de Estados Unidos. Protagonizada en su primera temporada por Matthew McConaughey y Woody Harrelson, la serie es conocida por su estilo cinematográfico y profundas tramas psicológicas.', 24, 'Matthew McConaughey, Woody Harrelson', 'Inglés y Español').
serie(59, 'The Sinner', suspenso, 2017, 'La serie sigue al detective Harry Ambrose mientras investiga crímenes impactantes cometidos por individuos aparentemente normales, desentrañando sus motivos oscuros y secretos profundos. Protagonizada por Bill Pullman y Jessica Biel, la serie ofrece intensos misterios en cada temporada.', 32, 'Bill Pullman, Jessica Biel', 'Inglés y Español').
serie(60, 'Mr. Robot', suspenso, 2015, 'Elliot Alderson, un joven programador con trastorno de ansiedad social, es reclutado por un grupo de hacktivistas para derribar a las corporaciones más poderosas del mundo. Protagonizada por Rami Malek y Christian Slater, la serie es conocida por su representación realista del hacking y sus giros narrativos.', 45, 'Rami Malek, Christian Slater', 'Inglés y Español').
serie(61, 'Homeland', suspenso, 2011, 'Carrie Mathison, una agente de la CIA con trastorno bipolar, cree que un marine estadounidense, rescatado después de años de cautiverio, se ha convertido en un terrorista de Al Qaeda. Protagonizada por Claire Danes y Damian Lewis, la serie es un thriller de espionaje lleno de tensión y sorpresas.', 96, 'Claire Danes, Damian Lewis', 'Inglés y Español').
serie(62, 'The Night Of', suspenso, 2016, 'Nasir Khan, un joven estudiante, se ve atrapado en el sistema judicial de Nueva York después de ser acusado de un brutal asesinato. Protagonizada por Riz Ahmed y John Turturro, la serie es un profundo y perturbador drama criminal que explora temas de raza, justicia y corrupción.', 8, 'Riz Ahmed, John Turturro', 'Inglés y Español').
serie(63, 'Big Little Lies', suspenso, 2017, 'En la idílica comunidad de Monterey, California, un grupo de madres se ve envuelto en un misterio de asesinato, revelando secretos oscuros y complejas relaciones. Protagonizada por Reese Witherspoon, Nicole Kidman y Shailene Woodley, la serie es un intrigante drama psicológico.', 14, 'Reese Witherspoon, Nicole Kidman, Shailene Woodley', 'Inglés y Español').
serie(64, 'You', suspenso, 2018, 'Joe Goldberg, un librero con tendencias obsesivas y violentas, se enamora y se obsesiona con varias mujeres a lo largo de la serie, utilizando las redes sociales y otros métodos para controlar sus vidas. Protagonizada por Penn Badgley y Victoria Pedretti, la serie es un thriller psicológico con giros inesperados.', 30, 'Penn Badgley, Victoria Pedretti', 'Inglés y Español').
%animacion
serie(65, 'Rick and Morty', animación, 2013, 'Rick Sanchez, un científico loco y alcohólico, lleva a su nieto Morty en peligrosas aventuras interdimensionales, mientras lidian con la vida familiar y los dilemas existenciales. Protagonizada por Justin Roiland y Chris Parnell, la serie es conocida por su humor irreverente y sus complejas tramas de ciencia ficción.', 61, 'Justin Roiland, Chris Parnell', 'Inglés y Español').
serie(66, 'BoJack Horseman', animación, 2014, 'BoJack Horseman, una estrella de televisión de los años 90, lucha con la depresión y la adicción mientras intenta relanzar su carrera en Hollywood. Protagonizada por Will Arnett y Aaron Paul, la serie es una mezcla de comedia y drama con profundos comentarios sociales.', 77, 'Will Arnett, Aaron Paul', 'Inglés y Español').
serie(67, 'Gravity Falls', animación, 2012, 'Los gemelos Dipper y Mabel Pines pasan el verano con su tío Stan en el misterioso pueblo de Gravity Falls, donde descubren secretos paranormales y conspiraciones. Protagonizada por Jason Ritter y Kristen Schaal, la serie es conocida por su humor ingenioso y su narrativa intrigante.', 40, 'Jason Ritter, Kristen Schaal', 'Inglés y Español').
serie(68, 'Adventure Time', animación, 2010, 'Finn, un joven héroe, y su perro mágico Jake, viven en la Tierra de Ooo, donde enfrentan extrañas criaturas y viven fantásticas aventuras. Protagonizada por Jeremy Shada y John DiMaggio, la serie es famosa por su creatividad, humor absurdo y temas profundos.', 283, 'Jeremy Shada, John DiMaggio', 'Inglés y Español').
serie(69, 'The Simpsons', animación, 1989, 'La familia Simpson, compuesta por Homer, Marge, Bart, Lisa y Maggie, vive en la ciudad ficticia de Springfield, donde sus vidas cotidianas son satirizadas con humor y comentarios sociales. Protagonizada por Dan Castellaneta y Julie Kavner, la serie es una de las más longevas y reconocidas de la televisión.', 750, 'Dan Castellaneta, Julie Kavner', 'Inglés y Español').
serie(70, 'Futurama', animación, 1999, 'Philip J. Fry, un repartidor de pizzas del siglo XX, se despierta en el futuro después de ser congelado criogénicamente. Se une a una tripulación de reparto interplanetario y vive aventuras en el espacio. Protagonizada por Billy West y Katey Sagal, la serie es conocida por su humor inteligente y referencias culturales.', 140, 'Billy West, Katey Sagal', 'Inglés y Español').
serie(71, 'Bobs Burgers', animación, 2011, 'Bob Belcher y su peculiar familia administran un restaurante de hamburguesas, enfrentando desafíos cotidianos y cómicas situaciones. Protagonizada por H. Jon Benjamin y John Roberts, la serie es conocida por su humor familiar y personajes entrañables.', 238, 'H. Jon Benjamin, John Roberts', 'Inglés y Español').
serie(72, 'Archer', animación, 2009, 'Sterling Archer, un espía egocéntrico y su equipo trabajan en la agencia de espionaje ISIS, enfrentando misiones peligrosas y disfunciones personales. Protagonizada por H. Jon Benjamin y Judy Greer, la serie es una comedia de espionaje con diálogos ingeniosos y humor adulto.', 126, 'H. Jon Benjamin, Judy Greer', 'Inglés y Español').
serie(73, 'Family Guy', animación, 1999, 'La vida de la disfuncional familia Griffin, compuesta por Peter, Lois, Meg, Chris, Stewie y su perro Brian, es satirizada con humor negro y referencias culturales. Protagonizada por Seth MacFarlane y Alex Borstein, la serie es conocida por su estilo irreverente y provocador.', 400+, 'Seth MacFarlane, Alex Borstein', 'Inglés y Español').
%policial
serie(74, 'Breaking Bad', policial, 2008, 'Walter White, un profesor de química convertido en fabricante de metanfetaminas, se asocia con su exalumno Jesse Pinkman para asegurar el futuro financiero de su familia, mientras se enfrenta a los desafíos del mundo criminal. Protagonizada por Bryan Cranston y Aaron Paul, la serie es un intenso drama criminal lleno de suspense.', 62, 'Bryan Cranston, Aaron Paul', 'Inglés y Español').
serie(75, 'The Wire', policial, 2002, 'Ambientada en Baltimore, la serie explora la interacción entre las fuerzas policiales, los traficantes de drogas, el sistema escolar y los medios de comunicación, presentando un retrato realista y profundo de la ciudad. Protagonizada por Dominic West y Idris Elba, la serie es aclamada por su realismo y complejidad narrativa.', 60, 'Dominic West, Idris Elba', 'Inglés y Español').
serie(76, 'True Detective', policial, 2014, 'Cada temporada presenta una historia y un elenco diferente, explorando oscuros crímenes en varios lugares de Estados Unidos. Protagonizada en su primera temporada por Matthew McConaughey y Woody Harrelson, la serie es conocida por su estilo cinematográfico y profundas tramas psicológicas.', 24, 'Matthew McConaughey, Woody Harrelson', 'Inglés y Español').
serie(77, 'Mindhunter', policial, 2017, 'Ambientada en los años 70, la serie sigue a dos agentes del FBI, Holden Ford y Bill Tench, que desarrollan técnicas de perfilación criminal al entrevistar a asesinos en serie. Protagonizada por Jonathan Groff y Holt McCallany, la serie es un thriller psicológico basado en hechos reales.', 19, 'Jonathan Groff, Holt McCallany', 'Inglés y Español').
serie(78, 'Narcos', policial, 2015, 'La serie sigue el ascenso y la caída del infame narcotraficante colombiano Pablo Escobar y el esfuerzo de la DEA por capturarlo. Protagonizada por Wagner Moura y Pedro Pascal, la serie es una tensa y dramática representación del tráfico de drogas en América Latina.', 30, 'Wagner Moura, Pedro Pascal', 'Inglés y Español').
serie(79, 'Dexter', policial, 2006, 'Dexter Morgan, un analista forense especializado en salpicaduras de sangre para el Departamento de Policía de Miami, lleva una doble vida como asesino en serie que caza a criminales que han escapado de la justicia. Protagonizada por Michael C. Hall y Jennifer Carpenter, la serie es un oscuro y emocionante thriller.', 96, 'Michael C. Hall, Jennifer Carpenter', 'Inglés y Español').
serie(80, 'Sherlock', policial, 2010, 'Una adaptación moderna de los clásicos de Arthur Conan Doyle, donde el detective Sherlock Holmes y su compañero, el Dr. John Watson, resuelven crímenes en el Londres contemporáneo. Protagonizada por Benedict Cumberbatch y Martin Freeman, la serie es conocida por su ingenio y emocionante narrativa.', 13, 'Benedict Cumberbatch, Martin Freeman', 'Inglés y Español').
serie(81, 'Brooklyn Nine-Nine', policial, 2013, 'Jake Peralta, un talentoso pero inmaduro detective, y su ecléctico grupo de colegas en la comisaría 99 de Brooklyn enfrentan crímenes mientras navegan por la vida profesional y personal. Protagonizada por Andy Samberg y Andre Braugher, la serie es una comedia de situaciones con elementos de drama policial.', 153, 'Andy Samberg, Andre Braugher', 'Inglés y Español').

serie(82, 'CSI: Crime Scene Investigation', policial, 2000, 'Un equipo de científicos forenses y detectives en Las Vegas trabaja para resolver crímenes utilizando la última tecnología en análisis de evidencia. Protagonizada por William Petersen y Marg Helgenberger, la serie es conocida por su enfoque en los procedimientos científicos y la resolución de crímenes.', 337, 'William Petersen, Marg Helgenberger', 'Inglés y Español').

serie(83, 'Law & Order: Special Victims Unit', policial, 1999, 'La Unidad de Víctimas Especiales del Departamento de Policía de Nueva York investiga crímenes de naturaleza sexual y de abuso. Protagonizada por Mariska Hargitay y Christopher Meloni, la serie es reconocida por su tratamiento serio de temas delicados y su narrativa judicial.', 500, 'Mariska Hargitay, Christopher Meloni', 'Inglés y Español').

%Genero_peliculas




todas_las_peliculas :-
    serie(ID, Titulo, Categoria, Anio, Sinopsis, Duracion, Actores, Idioma),
    format('ID: ~w~n', [ID]),
    format('Título: ~w~n', [Titulo]),
    format('Categoría: ~w~n', [Categoria]),
    format('Año: ~w~n', [Anio]),
    format('Sinopsis: ~w~n', [Sinopsis]),
    format('Duración: ~w minutos~n', [Duracion]),
    format('Actores: ~w~n', [Actores]),
    format('Idioma: ~w~n', [Idioma]),
    nl,
    fail.